/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import cambodia.raven.DateChooser;
import controller.VeritabaniYonetici;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mert
 */
public class Anasayfa extends javax.swing.JFrame {

    VeritabaniYonetici vy = new VeritabaniYonetici();
    String girisYapanAdmin;
    DefaultTableModel dtm = new DefaultTableModel();
    ButtonGroup yakitBG = new ButtonGroup();
    ButtonGroup vitesBG = new ButtonGroup();

    
    
    public Anasayfa() {
        initComponents();
        arabaTable.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"Marka", "Model", "Yıl", "Yakıt", "Vites", "Km", "Kategori", "Ucret", "Plaka", "Durum", "ID"});
        yakitBG.add(dizelRB);
        yakitBG.add(benzinRB);
        vitesBG.add(manuelRB);
        vitesBG.add(otomatikRB);
        try {
            vy.butunArabalariListele(arabaTable);
        } catch (SQLException ex) {}
    }
    
    public Anasayfa(String girisYapanAdmin){
        initComponents();
        this.girisYapanAdmin = girisYapanAdmin;
        arabaTable.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"Marka", "Model", "Yıl", "Yakıt", "Vites", "Km", "Kategori", "Ucret", "Plaka", "Durum", "ID"});
        yakitBG.add(dizelRB);
        yakitBG.add(benzinRB);
        vitesBG.add(manuelRB);
        vitesBG.add(otomatikRB);
        try {
            vy.butunArabalariListele(arabaTable);
        } catch (SQLException ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arabaTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        plakaTF = new javax.swing.JTextField();
        plakayaGoreAraBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dizelRB = new javax.swing.JRadioButton();
        benzinRB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        otomatikRB = new javax.swing.JRadioButton();
        manuelRB = new javax.swing.JRadioButton();
        baslangicTarihiDC = new cambodia.raven.DateChooser();
        bitisTarihiDC = new cambodia.raven.DateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tariheGoreAraBtn = new javax.swing.JButton();
        kiralaBtn = new javax.swing.JButton();
        bakimaGonderBtn = new javax.swing.JButton();
        teslimAlBtn = new javax.swing.JButton();
        bakimdanAlBtn = new javax.swing.JButton();
        arabaEkleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arabaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        arabaTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                arabaTableFocusLost(evt);
            }
        });
        arabaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arabaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arabaTable);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Plaka:");

        plakayaGoreAraBtn.setText("Ara");
        plakayaGoreAraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plakayaGoreAraBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(plakaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plakayaGoreAraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plakaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(plakayaGoreAraBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dizelRB.setText("Dizel");

        benzinRB.setText("Benzin & LPG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(benzinRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dizelRB)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dizelRB)
                    .addComponent(benzinRB))
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        otomatikRB.setText("Otomatik");

        manuelRB.setText("Manuel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(otomatikRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manuelRB)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otomatikRB)
                    .addComponent(manuelRB))
                .addGap(25, 25, 25))
        );

        baslangicTarihiDC.setBackground(new java.awt.Color(73, 125, 107));

        bitisTarihiDC.setBackground(new java.awt.Color(73, 125, 107));

        jLabel1.setText("Başlangıç Tarihi");

        jLabel2.setText("Bitiş Tarihi");

        tariheGoreAraBtn.setText("Ara");
        tariheGoreAraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tariheGoreAraBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baslangicTarihiDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bitisTarihiDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(tariheGoreAraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tariheGoreAraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bitisTarihiDC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(baslangicTarihiDC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        kiralaBtn.setText("Kirala");
        kiralaBtn.setEnabled(false);
        kiralaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiralaBtnActionPerformed(evt);
            }
        });

        bakimaGonderBtn.setText("Bakıma Gönder");
        bakimaGonderBtn.setEnabled(false);
        bakimaGonderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakimaGonderBtnActionPerformed(evt);
            }
        });

        teslimAlBtn.setText("Teslim Al");
        teslimAlBtn.setEnabled(false);
        teslimAlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teslimAlBtnActionPerformed(evt);
            }
        });

        bakimdanAlBtn.setText("Bakımdan Al");
        bakimdanAlBtn.setEnabled(false);
        bakimdanAlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakimdanAlBtnActionPerformed(evt);
            }
        });

        arabaEkleBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        arabaEkleBtn.setText("Araba Ekle");
        arabaEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabaEkleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(arabaEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(kiralaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(teslimAlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bakimaGonderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bakimdanAlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arabaEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kiralaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakimaGonderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teslimAlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakimdanAlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tariheGoreAraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tariheGoreAraBtnActionPerformed
        String baslangicTarihi = baslangicTarihiDC.getSelectedDate(DateChooser.GET_YEAR) + "-" + baslangicTarihiDC.getSelectedDate(DateChooser.GET_MONTH) + "-" + 
                                                                                                 baslangicTarihiDC.getSelectedDate(DateChooser.GET_DAY);
        String bitisTarihi = bitisTarihiDC.getSelectedDate(DateChooser.GET_YEAR) + "-" + bitisTarihiDC.getSelectedDate(DateChooser.GET_MONTH) + "-" + 
                                                                                                 bitisTarihiDC.getSelectedDate(DateChooser.GET_DAY);
        
        vy.tariheGoreAra(benzinRB.isSelected(), dizelRB.isSelected(), manuelRB.isSelected(), otomatikRB.isSelected(), 
                         baslangicTarihi, bitisTarihi, arabaTable);
    }//GEN-LAST:event_tariheGoreAraBtnActionPerformed

    private void arabaEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabaEkleBtnActionPerformed
        ArabaEkle arabaEkle = new ArabaEkle();
        arabaEkle.show();
    }//GEN-LAST:event_arabaEkleBtnActionPerformed

    private void plakayaGoreAraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plakayaGoreAraBtnActionPerformed
        try {
            vy.plakayaGoreListele(plakaTF.getText(), arabaTable);
        } catch (SQLException ex) {}
    }//GEN-LAST:event_plakayaGoreAraBtnActionPerformed

    private void arabaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arabaTableMouseClicked
        if(arabaTable.getSelectedRow() == -1){
            disableButtons();
        }
        if(arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 6).equals("Uygun")){
            bakimaGonderBtn.setEnabled(true);
            kiralaBtn.setEnabled(true);
            bakimdanAlBtn.setEnabled(false);
            teslimAlBtn.setEnabled(false);
        }
        else if(arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 6).equals("Kirada")){
            teslimAlBtn.setEnabled(true);
            kiralaBtn.setEnabled(true);
            bakimaGonderBtn.setEnabled(false);
            bakimdanAlBtn.setEnabled(false);
        }
        else if(arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 6).equals("Tamirde")){
            bakimdanAlBtn.setEnabled(true);
            kiralaBtn.setEnabled(true);
            bakimaGonderBtn.setEnabled(false);
            teslimAlBtn.setEnabled(false);
        }
    }//GEN-LAST:event_arabaTableMouseClicked

    private void arabaTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arabaTableFocusLost
        //disableButtons();
    }//GEN-LAST:event_arabaTableFocusLost

    private void kiralaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiralaBtnActionPerformed
        if(arabaTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Lütfen kiralamak için bir araç seçiniz.");
            System.out.println(arabaTable.getSelectedRow());
            return;
        }
        ArabaKirala arabaKirala;
        try {
            arabaKirala = new ArabaKirala(girisYapanAdmin, (int)arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 0), 
                                          (int)arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 7));
            arabaKirala.show();
        } catch (SQLException ex) {}
    }//GEN-LAST:event_kiralaBtnActionPerformed

    private void bakimdanAlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakimdanAlBtnActionPerformed
        boolean basarili = vy.durumDegistir("Uygun", (int)arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 0));
        if(basarili)
            JOptionPane.showMessageDialog(rootPane, "Bakımdan alma başarılı.");
        else
            JOptionPane.showMessageDialog(rootPane, "Bakımdan alma başarısız.");
    }//GEN-LAST:event_bakimdanAlBtnActionPerformed

    private void teslimAlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teslimAlBtnActionPerformed
        if(arabaTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Lütfen teslim almak için bir araç seçiniz.");
            System.out.println(arabaTable.getSelectedRow());
            return;
        }
        ArabaIade arabaIade = new ArabaIade((int)arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 0));
        arabaIade.show();
    }//GEN-LAST:event_teslimAlBtnActionPerformed

    private void bakimaGonderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakimaGonderBtnActionPerformed
        BakimaGonder bakimaGonder = new BakimaGonder((int)arabaTable.getModel().getValueAt(arabaTable.getSelectedRow(), 0));
        bakimaGonder.show();
    }//GEN-LAST:event_bakimaGonderBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arabaEkleBtn;
    private javax.swing.JTable arabaTable;
    private javax.swing.JButton bakimaGonderBtn;
    private javax.swing.JButton bakimdanAlBtn;
    private cambodia.raven.DateChooser baslangicTarihiDC;
    private javax.swing.JRadioButton benzinRB;
    private cambodia.raven.DateChooser bitisTarihiDC;
    private javax.swing.JRadioButton dizelRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kiralaBtn;
    private javax.swing.JRadioButton manuelRB;
    private javax.swing.JRadioButton otomatikRB;
    private javax.swing.JTextField plakaTF;
    private javax.swing.JButton plakayaGoreAraBtn;
    private javax.swing.JButton tariheGoreAraBtn;
    private javax.swing.JButton teslimAlBtn;
    // End of variables declaration//GEN-END:variables

    private void disableButtons() {
        kiralaBtn.setEnabled(false);
        teslimAlBtn.setEnabled(false);
        bakimaGonderBtn.setEnabled(false);
        bakimdanAlBtn.setEnabled(false);
    }
}
